version: "3"
services:
  fluentd:
    container_name: fluentd
    user: root
    build:
      context: .
    image: fluentkafka
    volumes:
    - ./data/newraw/:/fluentd/log/files/
    - ./conf:/fluentd/etc/
    - ./output:/output/
    logging:
      driver: "local"
  producer:
    container_name: producer
    user: root
    image: producer 
    volumes:
      - ./data/newraw/:/data/raw
    command: [php, batch_extract.php]
