version: '3'

services:
  producer:
    build:
      context: ./L1/
      dockerfile: Dockerfile
    container_name: producer_batch
    user: root
    image: producer
    volumes:
      - ./data/newraw/:/data/raw
      - ./L1/app:/app
    command: [ php, batch_extract.php ]
