version: '3'

services:
  zookeeper:
    image: zookeeper_clean
    container_name: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: kafka_clean
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  zoonavigator:
    image: elkozmon/zoonavigator
    container_name: zoonavigator
    ports:
      - "9000:9000"
    environment:
      HTTP_PORT: 9000
