version: '3'

services:
  zookeeper:
    image: zookeeper_clean
    container_name: zookeeper
    networks:
      - tap
    ports:
      - "2181:2181"
  k-init:
    image: kafka_init
    container_name: k-init
    networks:
      - tap
    ports:
      - "9091:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: k-financial
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  k-financial:
    image: kafka_clean
    container_name: k-financial
    networks:
      - tap
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: k-financial
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

networks:
  tap:
    driver: bridge
